# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieFlixApps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'RxSwift', '6.0.0'

  # Pods for MovieFlixApps

end
